site_name: Video Conferencing with Webex
repo_url: https://github.com/codemanas/video-conferencing-webex
site_author: Codemanas
nav:
  - Installation: index.md
  - Getting Started:
      - Basic Setup: basic-setup.md
      - Manual Setup: manual-setup.md
  - Shortcodes:
      - Show Single Meeting: shortcodes/single-event.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Rubik